name: CI Pipeline

on:
  push:

jobs:
  first_job:
  #first run on macos is 2min 1sec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'   # or whichever version you need
          cache: 'pip'
          
      # Step 3: Cache dependencies
      # - name: Cache pip dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run the file
        run: 
          # pip install papermill
          # papermill 0-DataingestParsing/2-dataparsingpdf.ipynb output.ipynb
          python 0-DataingestParsing/dl.py

  

